### ISSUE TITLE
Far scene terrain & lighting is glitchy when HDR rendering is enabled

### ISSUE THREAD

**Issue by auri0n** [SleepKiller/swbfii-shaderpatch#27]
More specifically, when HDR is enabled *and* in-game lighting quality is set to "high". For a while, I thought this had to do with the directional lighting bug that you're already aware of (and it still might), but I noticed that this issue, much like the water bug you fixed, has to do with draw distances. When zoomed in, the problem is completely gone:

https://i.imgur.com/uMsGcSM.mp4

As you can see, there are dark patches and the lighting is too bright. Apologies if I'm telling you a bunch of stuff you already know o.o

**Comment by SleepKiller** [comment]
> As you can see, there are dark patches and the lighting is too bright. Apologies if I'm telling you a 
> bunch of stuff you already know o.o
If there isn't a GitHub issue open for something always feel free to assume that I either don't know about it or worse I forgot about it because I didn't open an issue to remind me. 

So anyway thanks for letting me know and the video was a big help! I've yet to implement a fix but I have tracked down the problem. For anyone (including myself for future reference) interested here is what is going on here.

The near scene and far scene are drawn to separate render targets. The alpha channel of the near scene's render target stores the fade between them. They're blended together right before the game draws the near scene's transparent objects using a typical alpha blend.

`(Near Color * Near Alpha) + (Far Color * (1.0 - Near Alpha))`

The problem here is that because we use floating point formats while doing HDR rendering alpha values can end up outside the range `0` to `1`. SP normally deals with this by clamping the alpha value before outputting it. In this case however that solution isn't working and alpha values are finding their way to values they shouldn't be.

As far as I can tell this is a result of the [perpixeldiffuselighting](https://github.com/SleepKiller/swbfii-shaderpatch/blob/master/assets/core/src/perpixeldiffuselighting.fx) shader always outputing an alpha of `1.0` and when drawing lighting for terrain that alpha value is written out **additively** and `perpixeldiffuselighting` can be ran multiple times for the same piece of terrain to accumalte the lighting for all lights affecting it. 

Then the floating point render targets handle the rest and the alpha value shoots up above `1.0` and once it's time to blend the near scene and far scene we get these color problems from the bad alpha values.

Fixing this in a sane manner may require a special [skyfog](https://github.com/SleepKiller/swbfii-shaderpatch/blob/master/assets/core/src/skyfog.fx) shader for when we're doing HDR rendering. The special shader would sample both the near scene and far scene render targets itself and perform the blending between them itself. Unlike the framebuffer blending the game normally uses this would enable us to clamp the alpha value at blend time and hopefully fix this problem, at least partially.
